version: '3'

services:
  app:
    build:
      context: node
      dockerfile: Dockerfile.prod
    container_name: app
    networks:
      - node-network
    tty: true
    depends_on:
      - db
  db:
    image: mysql:latest
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network

  nginx:
    build:
      context: nginx
      dockerfile: Dockerfile.prod
    container_name: nginx
    ports:
      - 8080:80
    networks:
      - node-network
    depends_on:
      - app
networks:
  node-network:
    driver: bridge
